### ISSUE TITLE
On home page, make type2 search field only visible after type1 is selected.

### ISSUE THREAD

**Issue by rossgk2** [rossgk2/cs257#21]

**Comment by JuntaoZhong** [comment]
Maybe I should just have a "contain type" type of search.
Instead of type1 and type2, I just have something similar to the "ability", where I only have "contain ability"

**Comment by JuntaoZhong** [comment]
![image](https://user-images.githubusercontent.com/41411482/110284013-b8672c00-7fa6-11eb-8162-f12ca7f0008a.png)
Like this: if I select "fighting" as the type filter, fighting will appear in both type1 and type2
